import { LearningModule } from "./types";

export const aiAgents: LearningModule = {
  id: "ai-agents",
  title: "AI Agents & Tool Use",
  category: "AI Agents and Tool Use",
  prerequisites: ["llms", "rag"],
  tracks: ["modern-ai"],
  difficulty: 3,
  estimatedMinutes: 40,
  shortDescription: "A system architecture that lets an LLM pursue a goal across multiple steps by choosing from a set of external tools, executing them, and reasoning over the results in a loop until it can produce a grounded final answer.",
  learningObjectives: [
    "Explain what turns a plain LLM call into an agent: an action space of tools, a control loop, and a termination condition.",
    "Describe the mechanics of tool (function) calling, including how schemas constrain arguments and how results are fed back as observations.",
    "Trace through the ReAct pattern's Thought, Action, Observation cycle on a concrete multi-step task.",
    "Identify common agent failure modes such as hallucinated arguments, non-converging loops, and error propagation, along with their mitigations.",
    "Evaluate when an agent's added complexity and cost is justified over a single LLM call, a RAG pipeline, or a deterministic pipeline."
  ],
  keyTerms: [
    {
      term: "Tool / Function Calling",
      definition: "A mechanism by which an LLM emits a structured request (a function name plus JSON arguments) that the surrounding system executes on its behalf, returning the result as an observation the model can read."
    },
    {
      term: "ReAct (Reason + Act)",
      definition: "A prompting pattern that interleaves free-text reasoning ('Thought') with tool invocations ('Action') and their results ('Observation'), so the model plans, acts, and revises its plan within the same loop."
    },
    {
      term: "Agent Loop",
      definition: "The think, act, observe, repeat control loop that turns a single static LLM call into a multi-step process capable of pursuing a goal across several tool interactions."
    },
    {
      term: "Tool Schema",
      definition: "A structured, typically JSON-Schema, specification of a tool's name, description, and typed arguments that tells the model exactly how it is permitted to call the tool."
    },
    {
      term: "Context / Memory Management",
      definition: "The practice of deciding what portion of an agent's growing history of thoughts, actions, and observations stays in the prompt window versus gets summarized, dropped, or stored externally as the loop runs longer."
    }
  ],
  misconceptions: [
    {
      claim: "An AI agent is just a chatbot with extra instructions telling it to 'act like an agent.'",
      correction: "An agent requires an explicit action space of tool schemas, a loop that executes actions and feeds real observations back into the model's context, and a termination condition. Prompting alone does not give a model the ability to call a search API or run code; that machinery has to be built around the LLM."
    },
    {
      claim: "More tools always make an agent more capable.",
      correction: "Every additional tool enlarges the action space the policy must choose correctly from, which raises the chance of picking the wrong tool or producing malformed arguments. A small, well-described, non-overlapping toolset generally outperforms dumping in dozens of overlapping tools."
    },
    {
      claim: "Because a ReAct loop 'reasons' at every step, an agent's final answer is automatically more trustworthy than a single LLM response.",
      correction: "Reasoning text is still generated by the same model and can be just as confidently wrong. What actually adds trust is grounding those steps in observations from real tool executions, not the act of writing out a 'Thought' by itself."
    }
  ],
  references: [
    {
      title: "ReAct: Synergizing Reasoning and Acting in Language Models",
      authors: "Shunyu Yao, Jeffrey Zhao, Dian Yu, Nan Du, Izhak Shafran, Karthik Narasimhan, Yuan Cao",
      url: "https://arxiv.org/abs/2210.03629",
      type: "paper"
    },
    {
      title: "Toolformer: Language Models Can Teach Themselves to Use Tools",
      authors: "Timo Schick, Jane Dwivedi-Yu, Roberto Dessi, et al.",
      url: "https://arxiv.org/abs/2302.04761",
      type: "paper"
    },
    {
      title: "Function Calling and Tool Use",
      authors: "OpenAI Documentation",
      url: "https://platform.openai.com/docs/guides/function-calling",
      type: "documentation"
    }
  ],
  failureModes: [
    {
      name: "Hallucinated Tool Arguments",
      description: "The model calls a real, well-specified tool but fabricates or malforms the arguments (a wrong identifier, an invented parameter, mismatched units), so the tool either errors out or silently returns a wrong result the agent treats as ground truth.",
      mitigation: "Validate every argument against the tool's JSON schema before executing it, reject and re-prompt on schema violations, and where the provider supports it, constrain generation with structured or JSON-mode decoding."
    },
    {
      name: "Infinite or Non-Converging Loops",
      description: "The agent keeps re-issuing similar queries or oscillates between two actions without making progress toward the goal, because nothing in the loop forces convergence.",
      mitigation: "Enforce a hard step budget and a token or cost budget, detect repeated action-observation pairs and break early, and prompt the agent to explicitly track what it has already tried."
    },
    {
      name: "Error Propagation Without Recovery",
      description: "An early tool call returns a wrong or partial result, such as a bad search hit or a stale cache entry, and the agent treats it as fact, compounding the mistake through every subsequent step instead of noticing and re-querying.",
      mitigation: "Give the agent explicit permission and prompting to doubt an observation, retry with a reformulated query, or call a verification tool or a human reviewer before committing to a final answer."
    }
  ],
  pros: [
    "Composes multiple tools and reasoning steps to solve tasks no single retrieval or generation call could, adapting its plan as new information arrives.",
    "Grounds intermediate steps in real tool outputs such as search results, calculator results, and code execution, catching mistakes a pure language-only chain of thought would not.",
    "Generalizes to new tasks without new orchestration code: adding a tool to the registry with a good schema extends what the agent can do without touching the control flow."
  ],
  cons: [
    "Multiplies inference calls and tool round-trips, so latency and cost scale with the number of steps, and a stuck loop can burn both without producing an answer.",
    "Behaves nondeterministically and is harder to test than a fixed pipeline, since the exact sequence of tool calls can vary between runs on the same input.",
    "Introduces a much larger attack surface: a malicious or malformed tool result can inject instructions that the agent then unknowingly acts on."
  ],
  intuition: "Think about the difference between asking a knowledgeable friend a trivia question over text, which gets you one message and one answer, versus asking them to actually plan your trip: check flight prices, compare two hotels, and do some arithmetic against your budget. The second task cannot be answered from memory in one shot. Your friend has to take an action, see what comes back, and decide what to do next based on that result, possibly several times, before giving you a final answer. An AI agent puts a language model in that second role. Instead of only generating text, it is given a menu of tools it is allowed to call and a loop that runs it repeatedly, thinking, acting, and observing, until it has gathered enough real information to answer for real, or it has to admit it is stuck.",
  mathematics: "### The Agent Loop as a Policy over Actions\n\nAn agent pursues a goal $g$ (a natural-language instruction) by choosing a sequence of actions from an action space $\\mathcal{A} = \\mathcal{T} \\cup \\{\\text{Answer}\\}$, where $\\mathcal{T} = \\{\\text{search}, \\text{calculator}, \\text{code}, \\dots\\}$ is the set of callable tools and $\\text{Answer}(y)$ is the terminal action that returns the final response $y$. At step $t$ the agent has accumulated a history of its own past actions and the observations they produced:\n$$h_t = (a_1, o_1, a_2, o_2, \\dots, a_{t-1}, o_{t-1})$$\n\nThe agent is a stochastic policy over the next action, conditioned on the goal and the full history so far:\n$$\\pi_\\theta(a_t \\mid g, h_t)$$\nwhere $\\theta$ denotes the frozen weights of the underlying LLM, and the policy is realized entirely through in-context prompting rather than a trained value function. Each action $a_t = (\\text{name}, \\text{args})$ pairs a tool name with a structured arguments object; the environment executes it through an observation function\n$$o_t = \\mathcal{O}(s_t, a_t)$$\nwhere $s_t$ is the true, hidden state of the world, such as a document index, a filesystem, or a calculator's internal state. The agent never observes $s_t$ directly, only $o_t$, so the interaction is naturally a **partially observable Markov decision process (POMDP)**: the history $h_t$ is the agent's only substitute for a belief state, compressed implicitly into the LLM's context window rather than maintained as an explicit probability distribution over states.\n\n### Termination and Trajectory Probability\n\nThe episode ends the first time the policy samples $a_t = \\text{Answer}(y)$, or when a step budget $T_{\\max}$ is reached. The probability of an entire trajectory $\\tau = (a_1, o_1, \\dots, a_T, o_T)$ factorizes autoregressively over the interleaved action and observation sequence:\n$$P(\\tau \\mid g) = \\prod_{t=1}^{T} \\pi_\\theta(a_t \\mid g, h_t) \\cdot P(o_t \\mid s_t, a_t)$$\nThe policy term is entirely under the agent's control, and is exactly what prompting, few-shot examples, and fine-tuning shape. The observation term is fixed by the environment and is exactly where tool reliability, API errors, and stochastic search results inject variance that no amount of clever prompting can plan away.",
  fullDescription: "An AI agent couples a large language model with a defined set of external tools and a control loop, letting the model pursue a goal by interleaving reasoning with real actions such as searching, computing, calling APIs, and running code, rather than answering in a single shot. The dominant pattern, ReAct, has the model alternate between writing a short Thought, choosing an Action that is either a tool call or a final answer, and reading the Observation that action produces, feeding each observation back into the next reasoning step until the goal is satisfied or a step budget is exhausted.",
  codeSnippet: `"""
Minimal ReAct-style agent loop: think, choose a tool, observe the result,
and repeat until the model emits a final answer or the step budget runs out.
"""

TOOL_REGISTRY = {
    "search": {
        "description": "Look up a fact in a document index. Args: {query: str}.",
        "run": lambda args: web_search(args["query"]),
    },
    "calculator": {
        "description": "Evaluate a numeric expression. Args: {expression: str}.",
        "run": lambda args: str(evaluate_expression(args["expression"])),
    },
    "code": {
        "description": "Run a short Python snippet in a sandbox. Args: {source: str}.",
        "run": lambda args: run_sandboxed(args["source"]),
    },
}


def tool_schemas():
    """Build the tool specs the model sees when deciding its next action."""
    return [
        {"name": name, "description": spec["description"]}
        for name, spec in TOOL_REGISTRY.items()
    ]


def agent_loop(goal, llm, max_steps=6):
    """Run THINK, ACT, OBSERVE until the model answers or the budget runs out."""
    history = []

    for step in range(max_steps):
        thought, action = llm.decide(goal, history, tools=tool_schemas())

        if action["name"] == "answer":
            return action["args"]["text"]

        tool = TOOL_REGISTRY.get(action["name"])
        if tool is None:
            observation = "error: unknown tool '{}'".format(action["name"])
        else:
            try:
                observation = tool["run"](action["args"])
            except Exception as exc:
                observation = "error: {}".format(exc)

        history.append({"thought": thought, "action": action, "observation": observation})

    return "giving up: step budget exhausted without a final answer"`,
  relatedModules: ["llms", "rag", "fine-tuning"],
  tldr: [
    'An AI **agent** wraps an LLM in a loop that lets it choose tools, run them, and read the results, so it can pursue a goal across multiple steps instead of answering in one shot.',
    'The **ReAct** pattern makes this explicit: Thought (reason), Action (tool call or final answer), Observation (the real result), repeat.',
    'Tool calling constrains what the model can do to a defined **schema** of named tools and typed arguments, so its free-text output becomes a structured, executable request.',
    'The dominant failure modes are **hallucinated arguments**, **non-converging loops**, and **error propagation** — not a lack of reasoning ability.',
    'Agents cost more and are less predictable than a single call or a RAG pipeline, so reach for one only when the task genuinely needs to branch on intermediate results.',
  ],
  additionalSections: [
    {
      heading: 'Derivation: Tracing the ReAct Loop on a Multi-Step Question',
      content: `
Formalizing the loop is one thing; watching $h_t$ grow step by step makes it concrete. Take the goal $g = $ "What is the population of the capital of France, doubled?" This cannot be answered from a single fact lookup — it needs a lookup, then an arithmetic step, then a synthesis step, which is exactly the multi-action trajectory the policy $\\pi_\\theta(a_t \\mid g, h_t)$ is built to produce.

**Step 1.** History is empty, $h_1 = ()$. The model's Thought is "I need the capital of France, then its population." It samples the action $a_1 = \\text{search}(\\{\\text{query}: \\text{"capital of France"}\\})$. The environment executes the real search and returns the observation $o_1 = \\text{"Paris"}$.

**Step 2.** History is now $h_2 = (a_1, o_1)$. The Thought becomes "Now I need Paris's population." The model samples $a_2 = \\text{search}(\\{\\text{query}: \\text{"population of Paris"}\\})$, and the environment returns $o_2 = \\text{"about 2.1 million (city proper)"}$.

**Step 3.** History is $h_3 = (a_1, o_1, a_2, o_2)$. The Thought is "I have the population; now double it." The model samples $a_3 = \\text{calculator}(\\{\\text{expression}: \\text{"2.1 * 2"}\\})$, and the environment returns $o_3 = \\text{"4.2"}$.

**Step 4.** History is $h_4 = (a_1, o_1, a_2, o_2, a_3, o_3)$. With every fact it needs already sitting in the context window, the model samples the terminal action $a_4 = \\text{Answer}(\\text{"About 4.2 million."})$, and the trajectory ends.

Notice what changed at each step: the *action space* $\\mathcal{A}$ stayed fixed, but the *distribution* $\\pi_\\theta(a_t \\mid g, h_t)$ shifted because $h_t$ grew — each real observation narrowed down what the sensible next action was. A single LLM call, with no loop and no tool access, would have had to guess Paris's population from memory alone, with no way to check itself.
      `,
    },
    {
      heading: 'Tool Schemas, Argument Grounding, and the Hallucinated-Argument Failure Mode',
      content: `
A tool is only safely callable if the model is told exactly what arguments it accepts, and if the system checks what comes back before executing it. This is the job of a **tool schema**: a name, a natural-language description of when to use the tool, and a typed specification of its arguments, usually expressed as JSON Schema, e.g. \`{"name": "book_flight", "args": {"origin": "string (IATA code)", "date": "string (YYYY-MM-DD)"}}\`.

**Why schemas matter more than they look like they should.** The model does not literally "call a function" the way a compiler would; it generates *text* that looks like a function call, which the system then parses and executes. That text is sampled from the same next-token distribution as any other output, so it inherits the same failure mode as free-text generation: the model can emit a plausible-looking argument that is subtly wrong, e.g. writing \`"JFK Airport"\` where the schema requires the bare IATA code \`"JFK"\`. This is a **hallucinated argument**, and it is a generation error, not a tool error — the tool would have worked fine had the argument been well-formed.

**Grounding the arguments.** Two complementary defenses close most of this gap. First, *schema validation*: reject the call before executing it if the arguments do not type-check against the schema, and feed the validation error back as the observation so the model can retry with a corrected value, rather than letting a malformed call silently corrupt downstream state. Second, *constrained decoding*: where the serving stack supports it, force the model's output to conform to the schema's grammar at the token level (structured or JSON-mode generation), which prevents many malformed calls from being sampled in the first place rather than catching them after the fact.

**Why this compounds in long loops.** A single hallucinated argument early in a trajectory does not just fail once — its incorrect observation becomes part of $h_t$ for every subsequent step, so the model reasons forward from a false premise unless something forces it to notice and re-query. This is why production agents pair strict argument validation with an explicit instruction to treat any tool error or suspicious result as a reason to retry rather than to proceed.
      `,
    },
  ],
  comparisons: [
    {
      title: 'Single LLM Call vs AI Agent (Tool-Use Loop) vs Deterministic Pipeline',
      methods: ['Single LLM call', 'AI agent (tool-use loop)', 'Deterministic pipeline (fixed code)'],
      rows: [
        {
          dimension: 'Adapts action order to intermediate results',
          values: ['No — one shot, no branching', 'Yes — next action chosen from the latest observation', 'No — steps and order are fixed at design time'],
        },
        {
          dimension: 'Handles unforeseen multi-step goals',
          values: ['Poorly — must fit in one prompt and response', 'Well — plans and composes tools on the fly', "Only for cases the pipeline's author anticipated"],
        },
        {
          dimension: 'Predictability and debuggability',
          values: ['High — same prompt, similar output', 'Lower — tool-call sequence varies run to run', 'Highest — same input always takes the same path'],
        },
        {
          dimension: 'Cost per task',
          values: ['Lowest — one inference call', 'Higher — multiple LLM calls plus tool latency', 'Lowest — no LLM calls at runtime, or just one'],
        },
        {
          dimension: 'Typical failure mode',
          values: ['Hallucinated fact with no grounding', 'Hallucinated tool arguments or a non-converging loop', 'Silent wrong answer outside the cases it was built for'],
        },
        {
          dimension: 'When to use',
          values: ['Answerable from the prompt or context alone', 'Multi-step, tool-dependent tasks with a bounded budget', 'Well-understood, repeatable workflows needing determinism'],
        },
      ],
      takeaway: 'Reach for an agent only when the task genuinely needs to branch on intermediate results across multiple tools; if one call suffices, use a single LLM (or RAG) call, and if the workflow is fixed and must be reproducible, encode it as deterministic code instead of a learned policy.',
    },
  ],
  usageGuidance: {
    useWhen: [
      'The task decomposes into multiple **dependent sub-steps** that cannot be resolved by a single retrieval or generation call, such as "look up X, compute Y from it, then verify Z."',
      'The task requires interacting with **live external systems** — databases, APIs, code execution, filesystems — where the right next action depends on what a previous call returned.',
      'You need the model to **dynamically choose among several tools** rather than following one fixed, hand-coded pipeline.',
      'The cost of an extra reasoning-and-tool round trip is acceptable relative to the value of a verified, grounded, multi-step answer.',
    ],
    avoidWhen: [
      'The task is answerable from a **single retrieval or generation call** — the loop only adds latency and cost with no benefit.',
      'Determinism and auditability are paramount and every step must be exactly reproducible — a fixed pipeline is safer than a learned policy.',
      'The action space includes **high-stakes, irreversible operations** (payments, deletions) without a human-in-the-loop approval gate.',
      'You cannot bound the number of steps or tool calls, risking runaway cost or latency from a stuck loop in production.',
    ],
    rulesOfThumb: [
      'Start from the smallest fixed pipeline that solves the task; add an agent loop only once you have a concrete example the pipeline cannot handle.',
      'Constrain the action space with strict tool schemas and validate arguments before executing — most agent failures are malformed arguments, not bad reasoning.',
      'Always cap the loop with a step budget and a token or cost budget, and design a graceful "give up and ask for help" exit.',
      'Log the full history of thought, action, and observation per step — it is the only practical way to debug why an agent chose the path it did.',
    ],
  },
  caseStudies: [
    {
      title: 'The ReAct paper on interactive decision-making benchmarks',
      domain: 'Interactive text environments and knowledge-intensive QA',
      scenario: 'Yao et al. (2022) studied tasks where a language model must both reason about a goal and take real actions in an environment: household task completion in ALFWorld and online shopping in WebShop, alongside knowledge-intensive question answering on HotpotQA and fact verification on FEVER.',
      approach: 'They prompted a large language model with a small number of in-context examples that interleaved free-text Thoughts with Actions drawn from an environment-specific tool set, and fed each Action\'s real Observation back into the prompt for the next step, rather than relying purely on chain-of-thought reasoning or purely on action selection without reasoning.',
      outcome: 'ReAct outperformed both imitation-learning and reinforcement-learning baselines by an absolute success rate margin of roughly 34 points on ALFWorld and roughly 10 points on WebShop, using only one or two in-context examples for prompting, and it also reduced hallucinated reasoning compared to chain-of-thought-only prompting on the knowledge-intensive tasks by grounding intermediate steps in retrieved observations.',
      source: {
        title: 'ReAct: Synergizing Reasoning and Acting in Language Models',
        authors: 'Yao, S., Zhao, J., Yu, D., Du, N., Shafran, I., Narasimhan, K., Cao, Y.',
        url: 'https://arxiv.org/abs/2210.03629',
        type: 'paper',
      },
    },
  ],
  shortAnswerQuestions: [
    {
      question: "Compare a single RAG call to an agent loop for answering: \"What was Acme's Q3 revenue growth compared to the industry average?\" Discuss when the added complexity of an agent (multiple tool calls, iterative reasoning) is justified over a single retrieval-augmented generation call.",
      expectedAnswerRubric: "The answer should note that a single RAG call works well when one retrieval pass over one corpus contains everything needed to answer. This question is compound: it needs Acme's own Q3 figure (likely from one internal document set) and a separate industry-average figure (likely from a different external source), plus a computed comparison between the two. A single retrieval pass over one index may not surface both facts, and RAG has no built-in step for combining them. An agent loop is justified here because the task decomposes into dependent sub-steps: retrieve Acme's figure, retrieve the industry figure (possibly via a different tool or index), compute or compare the two, then synthesize an answer — exactly the multi-step, tool-composing pattern an agent loop, not a single RAG call, is designed for."
    }
  ],
  quiz: [
    {
      question: 'In the ReAct pattern, why is the "Observation" kept as a separate step rather than having the model reason and act in one shot?',
      options: [
        { text: "The observation comes from actually executing the action in the real environment, so the model cannot know it in advance — it must be appended to the history and reasoned over on the next step.", correct: true },
        { text: 'Language models are only able to process one step of reasoning per API call.', correct: false },
        { text: 'A Thought must always precede a search tool call specifically, and never any other tool.', correct: false },
        { text: 'Separating the steps halves the number of tokens the API provider charges for.', correct: false },
      ],
      explanation: 'A tool call has to actually run before its result is known — the model cannot predict a search result or a calculator output ahead of time. That is exactly why the loop is action-then-observation-then-next-action rather than a single forward pass: each observation is genuinely new information appended to the history that the next Thought conditions on.',
    },
    {
      question: 'A "book_flight" tool has a strict schema requiring a bare IATA airport code, but the model outputs the argument "JFK Airport" instead of "JFK". This is best described as:',
      options: [
        { text: 'A hallucinated or malformed tool argument — a generation error, not a tool failure.', correct: true },
        { text: 'A retrieval failure of the kind RAG systems experience.', correct: false },
        { text: 'Proof that the tool itself is broken and needs to be redesigned.', correct: false },
        { text: 'An unavoidable consequence of using function calling at all.', correct: false },
      ],
      explanation: 'The tool would have executed correctly with a valid argument; the model generated an argument that does not conform to the schema. That is a generation error in the policy\'s output, which schema validation and constrained decoding are designed to catch, not evidence that the tool or function calling itself is flawed.',
    },
    {
      question: "Why do production agent loops almost always enforce a maximum number of steps or a cost budget, rather than letting the loop run until the model naturally emits a final answer?",
      options: [
        { text: 'A policy that keeps re-planning or re-querying without converging can loop indefinitely, burning cost and latency with no guarantee of ever terminating.', correct: true },
        { text: 'LLM providers contractually cap the number of API calls allowed per conversation.', correct: false },
        { text: 'Each tool in the registry can only be invoked once per conversation by design.', correct: false },
        { text: 'Additional steps always strictly reduce the accuracy of the final answer.', correct: false },
      ],
      explanation: 'Nothing in the policy $\\pi_\\theta(a_t \\mid g, h_t)$ mathematically guarantees it will sample the terminal Answer action within a bounded number of steps — a stuck or oscillating agent can keep issuing actions forever. A hard step or cost budget, plus a graceful "give up" fallback, is the practical safeguard against that unbounded loop in production.',
    }
  ],
  review: {
    lastReviewed: '2026-07-11',
    reviewedBy: 'Suranjan',
    status: 'published',
  },
};
